# Generated by Django 4.1 on 2022-08-29 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nasa', '0002_alter_slider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['id']},
        ),
    ]
